export function egressDiagnosticsPayload(
  overrides: Readonly<Record<string, unknown>> = {},
): Record<string, unknown> {
  return {
    profile_id: 'egress-1',
    profile_name: 'Support proxy',
    profile_state: 'ready',
    health: 'ready',
    observation_mode: 'metadata_only',
    proof_level: 'runtime_launch_metadata',
    runtime_binding: 'docker:browser-1',
    runtime_assignment: 'ready',
    proxy_configured: true,
    proxy_auth_configured: false,
    bypass_rule_count: 1,
    custom_ca_configured: false,
    tls_interception_enabled: false,
    sensitive_log_sink_configured: false,
    proof: {
      profile_resolved: true,
      profile_ready: true,
      profile_reachability_collected: true,
      profile_reachability_healthy: true,
      profile_reachability_observed_at: '2026-08-07T10:00:00Z',
      profile_reachability_failure: null,
      proxy_launch_config_expected: true,
      bypass_rules_expected: 1,
      custom_ca_launch_config_expected: false,
      tls_interception_expected: false,
      sensitive_log_sink_declared: false,
      runtime_launch_observed: true,
      active_probe_collected: false,
      observed_public_ip: null,
      observed_tls_issuer: null,
      last_failure_reason: null,
    },
    warnings: [],
    observed_at: '2026-08-07T10:00:00Z',
    ...overrides,
  };
}
