import type { IdentityAccessReviewResponse } from '$lib/identity/identity-types';

export function identityAccessReviewFixture(): IdentityAccessReviewResponse {
  return {
    principal: {
      subject: 'user-1',
      issuer: 'https://identity.example/realms/pane',
      display_name: 'Demo Operator',
      client_id: null,
      principal_type: 'user',
    },
    generated_at: '2026-08-07T10:00:00.000Z',
    projects: [{
      id: 'project-1',
      name: 'Operations',
      description: 'Operations automation',
      labels: {},
      quotas: {},
      policy: {
        allowed_session_template_ids: [],
        allowed_egress_profile_ids: [],
        allowed_extension_ids: [],
        allowed_browser_context_ids: [],
        allowed_file_workspace_ids: [],
        allow_browser_uploads: true,
        allow_browser_downloads: true,
        allow_session_file_bindings: true,
        allow_manual_recordings: true,
        usage_budget_enforcement: 'warning_only',
      },
      state: 'active',
      usage: {
        project_id: 'project-1',
        active_sessions: 1,
        queued_sessions: 0,
        session_creations: 2,
        max_session_creations: null,
        max_active_sessions: 3,
        active_workflow_runs: 1,
        max_active_workflow_runs: 2,
        runtime_usage_ms: 1200,
        max_runtime_usage_ms: null,
        egress_rx_bytes: 100,
        egress_tx_bytes: 50,
        egress_total_bytes: 150,
        max_egress_total_bytes: null,
        retained_storage_bytes: 1024,
        max_retained_storage_bytes: null,
        alerts: [],
        observed_at: '2026-08-07T10:00:00.000Z',
      },
      created_at: '2026-08-01T10:00:00.000Z',
      updated_at: '2026-08-07T10:00:00.000Z',
    }],
    resource_counts: {
      projects: 1,
      service_principals: 1,
      identity_mappings: 1,
      sessions: 2,
      active_sessions: 1,
      session_templates: 1,
      browser_contexts: 1,
      egress_profiles: 1,
      credential_bindings: 1,
      file_workspaces: 1,
      workflow_definitions: 1,
      workflow_runs: 3,
      active_workflow_runs: 1,
      automation_tasks: 4,
      active_automation_tasks: 1,
      extension_definitions: 1,
      delegated_principals: 1,
    },
    identity_mappings: [{
      id: 'mapping-1',
      name: 'Demo operator access',
      description: 'Maps the demo operator to Operations',
      kind: 'user',
      issuer: 'https://identity.example/realms/pane',
      external_id: 'user-1',
      claim_name: null,
      service_principal_id: null,
      project_id: 'project-1',
      labels: { source: 'admin' },
      scopes: ['project:read'],
      state: 'active',
      last_seen_at: '2026-08-07T09:00:00.000Z',
      created_at: '2026-08-01T10:00:00.000Z',
      updated_at: '2026-08-07T09:00:00.000Z',
      effective_for_principal: true,
    }],
    unmapped_principal_signals: [{
      kind: 'group',
      issuer: 'https://identity.example/realms/pane',
      external_id: 'support',
      claim_name: null,
      display_name: 'Support',
      reason: 'group_without_project_mapping',
    }],
    service_principals: [{
      id: 'principal-1',
      name: 'MCP bridge',
      description: 'External automation identity',
      client_id: 'bpane-mcp-bridge',
      issuer: 'https://identity.example/realms/pane',
      labels: { purpose: 'automation' },
      scopes: ['session:delegate'],
      allowed_project_ids: ['project-1'],
      state: 'active',
      last_seen_at: '2026-08-07T09:00:00.000Z',
      last_delegated_at: '2026-08-07T09:30:00.000Z',
      created_at: '2026-08-01T10:00:00.000Z',
      updated_at: '2026-08-07T09:30:00.000Z',
      delegated_session_count: 2,
      active_delegated_session_count: 1,
      delegated_session_ids: ['session-1', 'session-2'],
    }],
    delegated_principals: [{
      client_id: 'bpane-mcp-bridge',
      issuer: 'https://identity.example/realms/pane',
      display_name: 'MCP bridge',
      registered: true,
      registered_service_principal_id: 'principal-1',
      state: 'active',
      session_count: 2,
      active_session_count: 1,
      session_ids: ['session-1', 'session-2'],
    }],
  };
}
