<script lang="ts">
  import { createWorkflowEventSubscriptionDraft, validateWorkflowEventSubscriptionDraft, type WorkflowEventSubscriptionDraft } from '$lib/workflow-events/workflow-event-view-model';
  import type { CreateWorkflowEventSubscriptionRequest } from '$lib/workflow-events/workflow-event-types';
  import AdminMessage from './AdminMessage.svelte';
  let { disabled = false, onSave }: { readonly disabled?: boolean; readonly onSave?: (request: CreateWorkflowEventSubscriptionRequest) => void | Promise<void> } = $props();
  let draft = $state<WorkflowEventSubscriptionDraft>(createWorkflowEventSubscriptionDraft()); const validation = $derived(validateWorkflowEventSubscriptionDraft(draft));
</script>
<section class="rounded-md border border-admin-border bg-admin-panel p-4 sm:p-5" data-testid="workflow-event-subscription-create-form"><div class="border-b border-admin-border pb-4"><h2 class="m-0 text-base font-semibold text-admin-ink">Outbound workflow events</h2><p class="m-0 mt-1 text-sm leading-6 text-admin-muted">Register a gateway-approved receiver and sign every delivery with a write-only HMAC secret.</p></div><form class="mt-5 grid gap-4" onsubmit={(event) => { event.preventDefault(); if (validation.request) void onSave?.(validation.request); }}>
  <label class="grid gap-1.5 text-sm"><span class="font-medium text-admin-ink">Name</span><input class="h-10 rounded-md border border-admin-border bg-white px-3 text-sm text-admin-ink outline-none focus:border-admin-accent" type="text" bind:value={draft.name} disabled={disabled} data-testid="workflow-event-subscription-name" />{#if validation.fieldErrors.name}<AdminMessage tone="error" density="compact" items={validation.fieldErrors.name} testId="workflow-event-subscription-name-error" />{/if}</label>
  <label class="grid gap-1.5 text-sm"><span class="font-medium text-admin-ink">Target URL</span><input class="h-10 rounded-md border border-admin-border bg-white px-3 font-mono text-xs text-admin-ink outline-none focus:border-admin-accent" type="url" bind:value={draft.targetUrl} disabled={disabled} placeholder="https://events.example/webhooks/browserpane" data-testid="workflow-event-subscription-target" /><span class="text-xs text-admin-muted">The gateway applies its configured outbound allowlist and public-address policy.</span>{#if validation.fieldErrors.targetUrl}<AdminMessage tone="error" density="compact" items={validation.fieldErrors.targetUrl} testId="workflow-event-subscription-target-error" />{/if}</label>
  <label class="grid gap-1.5 text-sm"><span class="font-medium text-admin-ink">Event types</span><textarea class="min-h-32 rounded-md border border-admin-border bg-white px-3 py-2 font-mono text-xs leading-5 text-admin-ink" bind:value={draft.eventTypesText} disabled={disabled} spellcheck="false" data-testid="workflow-event-subscription-event-types"></textarea><span class="text-xs text-admin-muted">One exact event type or namespace wildcard such as `workflow_run.*` per line.</span>{#if validation.fieldErrors.eventTypes}<AdminMessage tone="error" density="compact" items={validation.fieldErrors.eventTypes} testId="workflow-event-subscription-event-types-error" />{/if}</label>
  <label class="grid gap-1.5 text-sm"><span class="font-medium text-admin-ink">Signing secret</span><input class="h-10 rounded-md border border-admin-border bg-white px-3 text-sm text-admin-ink" type="password" bind:value={draft.signingSecret} disabled={disabled} autocomplete="new-password" data-testid="workflow-event-subscription-signing-secret" /><AdminMessage tone="warning" density="compact" title="Write-only value" message="The secret is retained for HMAC signing and never returned by list or detail APIs." />{#if validation.fieldErrors.signingSecret}<AdminMessage tone="error" density="compact" items={validation.fieldErrors.signingSecret} testId="workflow-event-subscription-signing-secret-error" />{/if}</label>
  <div class="flex justify-end border-t border-admin-border pt-4"><button class="inline-flex h-10 items-center justify-center rounded-md border border-admin-accent bg-admin-accent px-3 text-sm font-semibold text-white disabled:opacity-60" type="submit" disabled={disabled || !validation.valid} data-testid="workflow-event-subscription-create-submit">Create subscription</button></div>
</form></section>
