import { tick } from 'svelte'; import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'; import type { UnifiedAdminContext } from '$lib/auth/unified-admin-context'; import { byTestId, cleanupRenderedComponents, renderComponent } from '$lib/test-utils/svelte-component-test'; import WorkflowEventSubscriptionCreateRoute from './WorkflowEventSubscriptionCreateRoute.svelte';
beforeEach(() => window.history.replaceState(null, '', 'http://localhost:3000/admin-new/workflow-event-subscriptions/new')); afterEach(async () => { vi.unstubAllGlobals(); await cleanupRenderedComponents(); });
describe('WorkflowEventSubscriptionCreateRoute', () => {
  it('creates and navigates without retaining the signing secret in the response model', async () => { const navigateToSubscription = vi.fn(); const fetchImpl = vi.fn<typeof fetch>(async () => jsonResponse(subscriptionPayload(), 201)); vi.stubGlobal('fetch', fetchImpl); const target = renderComponent(WorkflowEventSubscriptionCreateRoute, { authContext: authContext(), navigateToSubscription }); await input(target, 'workflow-event-subscription-name', 'Workflow events'); await input(target, 'workflow-event-subscription-target', 'https://events.example/hook'); await input(target, 'workflow-event-subscription-signing-secret', 'write-only-secret'); byTestId(target, 'workflow-event-subscription-create-submit').click(); await vi.waitFor(() => expect(navigateToSubscription).toHaveBeenCalled()); expect(fetchImpl.mock.calls[0]?.[1]?.body).toContain('write-only-secret'); expect(JSON.stringify(navigateToSubscription.mock.calls[0]?.[0])).not.toContain('write-only-secret'); });
  it('shows gateway target validation without echoing signing material', async () => { vi.stubGlobal('fetch', vi.fn<typeof fetch>(async () => jsonResponse({ error: 'target URL is not allowed' }, 400))); const target = renderComponent(WorkflowEventSubscriptionCreateRoute, { authContext: authContext() }); await input(target, 'workflow-event-subscription-name', 'Workflow events'); await input(target, 'workflow-event-subscription-target', 'https://events.example/hook'); await input(target, 'workflow-event-subscription-signing-secret', 'sensitive-signing-secret'); byTestId(target, 'workflow-event-subscription-create-submit').click(); await vi.waitFor(() => expect(byTestId(target, 'workflow-event-subscription-create-error').textContent).toContain('not allowed')); expect(byTestId(target, 'workflow-event-subscription-create-error').textContent).not.toContain('sensitive-signing-secret'); });
});
async function input(target: HTMLElement, testId: string, value: string) { const element = byTestId(target, testId) as HTMLInputElement; element.value = value; element.dispatchEvent(new Event('input', { bubbles: true })); await tick(); }
function authContext(): UnifiedAdminContext { return { auth: { configured: true, authenticated: true, username: 'demo', accessToken: 'token', claims: null }, authConfig: null, accessTokenProvider: async () => 'shell-token', onAuthenticationFailure: vi.fn(), login: async () => {}, logout: async () => {} }; }
function jsonResponse(payload: unknown, status: number) { return new Response(JSON.stringify(payload), { status, headers: { 'content-type': 'application/json' } }); }
function subscriptionPayload() { return { id: 'subscription-1', name: 'Workflow events', target_url: 'https://events.example/hook', event_types: ['workflow_run.created'], has_signing_secret: true, deliveries_path: '/api/v1/workflow-event-subscriptions/subscription-1/deliveries', created_at: '2026-08-07T08:00:00.000Z', updated_at: '2026-08-07T09:00:00.000Z' }; }
